const countryLanguageCodes = [
    { country: "India", code: "IN", language: "Hindi" },
    { country: "United States", code: "US", language: "English" },
    { country: "United Kingdom", code: "GB", language: "English" },
    { country: "Spain", code: "ES", language: "Spanish" },
    { country: "France", code: "FR", language: "French" },
    { country: "Germany", code: "DE", language: "German" },
    { country: "China", code: "CN", language: "Chinese (Simplified)" },
    { country: "Taiwan", code: "TW", language: "Chinese (Traditional)" },
    { country: "Japan", code: "JP", language: "Japanese" },
    { country: "South Korea", code: "KR", language: "Korean" },
    { country: "Russia", code: "RU", language: "Russian" },
    { country: "Portugal", code: "PT", language: "Portuguese" },
    { country: "Italy", code: "IT", language: "Italian" },
    { country: "Netherlands", code: "NL", language: "Dutch" },
    { country: "Turkey", code: "TR", language: "Turkish" },
    { country: "Saudi Arabia", code: "SA", language: "Arabic" },
    { country: "Bangladesh", code: "BD", language: "Bengali" },
    { country: "Pakistan", code: "PK", language: "Urdu" },
    { country: "Greece", code: "GR", language: "Greek" },
    { country: "Israel", code: "IL", language: "Hebrew" },
    { country: "Thailand", code: "TH", language: "Thai" },
    { country: "Vietnam", code: "VN", language: "Vietnamese" },
    { country: "Poland", code: "PL", language: "Polish" },
    { country: "Sweden", code: "SE", language: "Swedish" },
    { country: "Czech Republic", code: "CZ", language: "Czech" },
    { country: "Romania", code: "RO", language: "Romanian" },
    { country: "Hungary", code: "HU", language: "Hungarian" },
    { country: "Finland", code: "FI", language: "Finnish" },
    { country: "Denmark", code: "DK", language: "Danish" },
    { country: "Norway", code: "NO", language: "Norwegian" },
    { country: "Malaysia", code: "MY", language: "Malay" },
    { country: "Indonesia", code: "ID", language: "Indonesian" },
    { country: "Philippines", code: "PH", language: "Filipino" },
    { country: "Slovakia", code: "SK", language: "Slovak" },
    { country: "Bulgaria", code: "BG", language: "Bulgarian" },
    { country: "Serbia", code: "RS", language: "Serbian" },
    { country: "Croatia", code: "HR", language: "Croatian" },
    { country: "Lithuania", code: "LT", language: "Lithuanian" },
    { country: "Latvia", code: "LV", language: "Latvian" },
    { country: "Estonia", code: "EE", language: "Estonian" },
    { country: "Iran", code: "IR", language: "Persian" },
    { country: "Kenya", code: "KE", language: "Swahili" },
    { country: "Ukraine", code: "UA", language: "Ukrainian" },
    { country: "Albania", code: "AL", language: "Albanian" },
    { country: "Georgia", code: "GE", language: "Georgian" },
    { country: "Macedonia", code: "MK", language: "Macedonian" },
    { country: "Armenia", code: "AM", language: "Armenian" },
    { country: "Bosnia and Herzegovina", code: "BA", language: "Bosnian" },
    { country: "Belarus", code: "BY", language: "Belarusian" },
    { country: "Iceland", code: "IS", language: "Icelandic" },
    { country: "Wales", code: "GB-WLS", language: "Welsh" },
    { country: "Ireland", code: "IE", language: "Irish" },
  ];
  

  export {countryLanguageCodes}
  