const languageCodes = [
    { name: "English", code: "en" },
    { name: "Hindi", code: "hi" },
    { name: "Spanish", code: "es" },
    { name: "French", code: "fr" },
    { name: "German", code: "de" },
    { name: "Chinese (Simplified)", code: "zh" },
    { name: "Chinese (Traditional)", code: "zh-TW" },
    { name: "Japanese", code: "ja" },
    { name: "Korean", code: "ko" },
    { name: "Russian", code: "ru" },
    { name: "Portuguese", code: "pt" },
    { name: "Italian", code: "it" },
    { name: "Dutch", code: "nl" },
    { name: "Turkish", code: "tr" },
    { name: "Arabic", code: "ar" },
    { name: "Bengali", code: "bn" },
    { name: "Punjabi", code: "pa" },
    { name: "Urdu", code: "ur" },
    { name: "Greek", code: "el" },
    { name: "Hebrew", code: "he" },
    { name: "Thai", code: "th" },
    { name: "Vietnamese", code: "vi" },
    { name: "Polish", code: "pl" },
    { name: "Swedish", code: "sv" },
    { name: "Czech", code: "cs" },
    { name: "Romanian", code: "ro" },
    { name: "Hungarian", code: "hu" },
    { name: "Finnish", code: "fi" },
    { name: "Danish", code: "da" },
    { name: "Norwegian", code: "no" },
    { name: "Malay", code: "ms" },
    { name: "Indonesian", code: "id" },
    { name: "Filipino", code: "fil" },
    { name: "Slovak", code: "sk" },
    { name: "Bulgarian", code: "bg" },
    { name: "Serbian", code: "sr" },
    { name: "Croatian", code: "hr" },
    { name: "Lithuanian", code: "lt" },
    { name: "Latvian", code: "lv" },
    { name: "Estonian", code: "et" },
    { name: "Persian", code: "fa" },
    { name: "Swahili", code: "sw" },
    { name: "Ukrainian", code: "uk" },
    { name: "Albanian", code: "sq" },
    { name: "Georgian", code: "ka" },
    { name: "Macedonian", code: "mk" },
    { name: "Armenian", code: "hy" },
    { name: "Bosnian", code: "bs" },
    { name: "Belarusian", code: "be" },
    { name: "Icelandic", code: "is" },
    { name: "Welsh", code: "cy" },
    { name: "Irish", code: "ga" },
  ];

  export{languageCodes}
  
 

  